# Generated by Django 2.2.5 on 2019-09-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('player_stat_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_stat_id', models.IntegerField()),
                ('stat_id', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StatDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_id', models.IntegerField()),
                ('stat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=255)),
                ('player_id', models.IntegerField()),
            ],
        ),
    ]
